name: Release

on:
  push:
    branches:
      - dev
    tags:
      - v*

jobs:
  TestPyPi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: TestPyPi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
      - run: uv publish --trusted-publishing always
